services:
  db:
    image: postgres:16
    container_name: briefex_db
    restart: always
    env_file:
      - src/briefex/config/.env
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    name: briefex_db_data
