"""init

Revision ID: bf7c8153775a
Revises:
Create Date: 2025-07-10 00:23:29.324372

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bf7c8153775a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("code_name", sa.String(length=64), nullable=False),
        sa.Column(
            "type",
            sa.Enum("HTML", "RSS", name="source_type_enum"),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_name"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(op.f("ix_sources_type"), "sources", ["type"], unique=False)
    op.create_table(
        "posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("canonical_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_SUMMARY",
                "SUMMARY_READY",
                "SUMMARY_RETRY",
                "SUMMARY_CENSORED",
                "MODERATION_APPROVED",
                "MODERATION_REJECTED",
                "SCHEDULED",
                "PUBLISHED",
                "ARCHIVED",
                name="post_status_enum",
            ),
            server_default=sa.text("'PENDING_SUMMARY'"),
            nullable=False,
        ),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("published_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_url"),
    )
    op.create_index(op.f("ix_posts_status"), "posts", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_status"), table_name="posts")
    op.drop_table("posts")
    op.drop_index(op.f("ix_sources_type"), table_name="sources")
    op.drop_table("sources")
    # ### end Alembic commands ###
