name: Lint

on:
  push:
  pull_request:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install ruff
        run: pip install "ruff==0.5.7"

      - name: Show versions
        run: |
          python -V
          ruff --version

      - name: Ruff format check
        run: ruff format --check .

      - name: Ruff lint
        run: ruff . --output-format=github
