name: Lint

on:
  pull_request:
  push:
    branches: [ "main" ]

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ruff:
    name: Ruff checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Ruff lint
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github

      - name: Ruff format
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check
