name: Lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==1.8.2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'

      - uses: abatilo/actions-poetry@v3

      - name: Install deps
        run: poetry install --with dev --no-interaction --no-root

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
